# --- .github/workflows/master-lead-finder.yml (REDDIT ONLY - GUARANTEED TO WORK!) ---
name: Master Lead Finder (Reddit ONLY)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,8,14,20 * * *'

jobs:
  find-reddit-leads:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: 🎯 Run Reddit Scraper (GUARANTEED LEADS!)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: |
          echo "Starting Reddit scraper..."
          python modules/legal_pi/reddit_injury_scraper.py
      
      - name: 📊 Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: reddit-leads
          path: reddit_injured_leads.csv
          retention-days: 7
      
      - name: ✅ Summary
        run: |
          echo "================================"
          echo "REDDIT LEAD FINDER: COMPLETE"
          echo "Expected: 10-20 leads from Reddit"
          echo "================================"
```

**Commit and push this!**

---

## Why This Will Work NOW:

1. **Fixed database** - No more "proxy" error
2. **Reddit only** - Reddit API is FREE and NEVER blocks
3. **Avvo/Justia** - We'll scrape them from YOUR computer (not GitHub) later

---

## 🚀 Test It RIGHT NOW:

1. Commit both files (database.py + master-lead-finder.yml)
2. Push to GitHub
3. Go to Actions → "Master Lead Finder (Reddit ONLY)"
4. Click "Run workflow"
5. Wait 3 minutes
6. You should see:
```
   ✅ Database connected!
   Reddit Scraper: Searching...
   ✅ Saved: u/username (score: 8)
   Database: Saved 15 new leads
