name: Mega Lead Collector

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,14 * * *'  # 2 AM and 2 PM

jobs:
  collect:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium
      
      - name: Run Anthropic Agent
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          FACEBOOK_EMAIL: ${{ secrets.FACEBOOK_EMAIL }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
        run: python mega_agent_anthropic_facebook.py
      
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: leads
          path: mega_leads_anthropic.csv
